name: build

on:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/**.yml'

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libsqlite3-dev zlib1g-dev

      - name: Build
        run: |
          cmake . -G Ninja
          ninja -j4

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MC2MT-linux
          path: bin/MC2MT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/MC2MT
          asset_name: MC2MT-linux
          tag: 'rolling'
          overwrite: true
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'


  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          release: false
          msystem: UCRT64
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-sqlite3

      - name: Build
        run: |
          cmake . -G Ninja -DCMAKE_EXE_LINKER_FLAGS="-static" -DZLIB_LIBRARY_RELEASE=/ucrt64/lib/libz.a -DSQLite3_LIBRARY=/ucrt64/lib/libsqlite3.a
          ninja -j4

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MC2MT-windows.exe
          path: bin/MC2MT.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/MC2MT.exe
          asset_name: MC2MT-windows.exe
          tag: 'rolling'
          overwrite: true
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update --auto-update
          brew install --display-times cmake ninja sqlite zlib

      - name: Build
        run: |
          cmake . -G Ninja
          ninja -j4

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MC2MT-macos
          path: bin/MC2MT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/MC2MT
          asset_name: MC2MT-macos
          tag: 'rolling'
          overwrite: true
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
